name: Rust

on:
  push:
    branches: [ "setup", "correction" ]
  pull_request:
    branches: [ "setup", "correction" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults :
      run:
        working-directory: data_types

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
